[workspace]
default-members = ["system-properties"]
members = ["system-properties", "system-properties-bindgen"]
resolver = "2"

[workspace.package]
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/chenxiaolong/system-properties"
